### ISSUE TITLE
Cannot install sagemaker-studio-image-build

### ISSUE THREAD

**Issue by PeskyPotato** [aws-samples/amazon-sagemaker-immersion-day#52]
When executing `#cell 00` in [bring-custom-container.ipnyb](https://github.com/aws-samples/amazon-sagemaker-immersion-day/blob/master/bring-custom-container.ipynb), `sagemaker-studio-image-build` fails to install, I've verified the packages successfuly installs on my local machine but not SageMaker Studio. This is the following error.

```
/opt/conda/lib/python3.7/site-packages/secretstorage/dhcrypto.py:16: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/opt/conda/lib/python3.7/site-packages/secretstorage/util.py:25: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
Collecting sagemaker-studio-image-build
  Using cached sagemaker_studio_image_build-0.6.0.tar.gz (13 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-3i1kn8pn/sagemaker-studio-image-build_a6da33aa92b34b98b5c2d69117b36e40/setup.py", line 33, in <module>
          package_data={"sagemaker_studio_image_build": ["*.yml", "data/**"]},
        File "/opt/conda/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/opt/conda/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 109, in setup
          _setup_distribution = dist = klass(attrs)
        File "/opt/conda/lib/python3.7/site-packages/setuptools/dist.py", line 466, in __init__
          for k, v in attrs.items()
        File "/opt/conda/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 293, in __init__
          self.finalize_options()
        File "/opt/conda/lib/python3.7/site-packages/setuptools/dist.py", line 885, in finalize_options
          for ep in sorted(loaded, key=by_order):
        File "/opt/conda/lib/python3.7/site-packages/setuptools/dist.py", line 884, in <lambda>
          loaded = map(lambda e: e.load(), filtered)
        File "/opt/conda/lib/python3.7/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 196, in load
          return functools.reduce(getattr, attrs, module)
      AttributeError: type object 'Distribution' has no attribute '_finalize_feature_opts'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by zapcity** [comment]
I didn't get that error. When I executed # cell 00 within `bring-custom-container.ipynb` from within Amazon Studio Sagemaker, I get:

```
# cell 00
!/opt/conda/bin/python -m pip install --upgrade pip
!pip install -q boto3==1.21.21
!pip install -q botocore==1.24.21
!pip install -q awscli==1.22.76
!pip install -Uq aiobotocore==2.2.0
!pip install -q sagemaker-studio-image-build
```

```
Requirement already satisfied: pip in /opt/conda/lib/python3.7/site-packages (22.1.2)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
awscli 1.25.8 requires botocore==1.27.8, but you have botocore 1.24.46 which is incompatible.
awscli 1.25.8 requires PyYAML<5.5,>=3.10, but you have pyyaml 6.0 which is incompatible.
awscli 1.25.8 requires rsa<4.8,>=3.1.2, but you have rsa 4.8 which is incompatible.
awscli 1.25.8 requires s3transfer<0.7.0,>=0.6.0, but you have s3transfer 0.5.2 which is incompatible.
aiobotocore 2.3.3 requires botocore<1.24.22,>=1.24.21, but you have botocore 1.24.46 which is incompatible.
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
awscli 1.25.8 requires botocore==1.27.8, but you have botocore 1.24.21 which is incompatible.
awscli 1.25.8 requires PyYAML<5.5,>=3.10, but you have pyyaml 6.0 which is incompatible.
awscli 1.25.8 requires rsa<4.8,>=3.1.2, but you have rsa 4.8 which is incompatible.
awscli 1.25.8 requires s3transfer<0.7.0,>=0.6.0, but you have s3transfer 0.5.2 which is incompatible.
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
s3fs 2022.5.0 requires aiobotocore~=2.3.0, but you have aiobotocore 2.2.0 which is incompatible.
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
```

Despite the warnings and errors, the notebook runs 100% OK.
